owner-repo: &owner-repo
  owner-repo: palantir/godel-okgo-asset-errcheck

excutor: &executor
  executor:
    name: go/darwin-linux-no-cgo
    version: 1.13.3-t27
    <<: *owner-repo

version: 2.1

orbs:
  go: palantir/go@0.0.13
  godel: palantir/godel@0.0.11

all-tags-filter: &all-tags-filter
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  verify-test-dist-publish:
    jobs:
      - godel/verify:
          name: verify
          <<: *executor
          <<: *all-tags-filter
          mod-cache: false
      - godel/test:
          name: test
          <<: *executor
          <<: *all-tags-filter
          mod-cache: false
      - godel/dist:
          name: dist
          <<: *executor
          <<: *all-tags-filter
          mod-cache: false
      - godel/bintray-publish:
          name: publish
          <<: *executor
          mod-cache: false
          bintray-subject: palantir
          bintray-repo: releases
          bintray-product: godel-okgo-asset-errcheck
          requires:
            - verify
            - test
            - dist
          filters:
            tags:
              only: /^v?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$/
            branches:
              ignore: /.*/
